name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Is this your first issue made? Make sure you are following the best practices and conventions!"
        pr-message: "Is this your first pull request? Make sure your pull request is named meaningfully and don't merge to dev without telling the team! Do not merge to release or master."
